### PR TITLE
Moved style sheet to external file, cleaned up style tags and html tags.

### PR DESCRIPTION
**Pull request by pjobson**
I saw you project on reddit, figured I'd send you a pull request.

This PR is for constructive criticism, I really enjoy your project!

This is a minor update which moves all the styles to an external file and cleans up the HTML a bit.

There were some minor errors in the HTML, for instance P tags don't really belong inside of A tags.  P tags are block level tags which can contain A tags, but not really vice versa.  P tags can work in A tags, it just isn't considered elegant.

I moved all of the styles into `styles.css` file, using a CSS file will make it easier for you to update in the long run, as you can make all of the modifications in one place, rather than doing a bunch of repetitive stuff in your HTML.

Feel free to use any, some, or none of my garbage.

Keep up the good work!

### CODE REVIEW

**Comment by mayeaux** [comment]
Thanks that looks a lot better, will merge that later today probably

**Comment by mayeaux** [comment]
Thanks for the PR!

**Comment by pjobson** [comment]
Happy to help!  There's a bit of a learning curve on electron.  I enjoy the simplicity of your project.  

Keep up the good work!

**Comment by mayeaux** [comment]
Actually I had to revert the changes. I was looking at a diff app instance when I checked out your branch so didn't actually see the changes (it looked to me like a carbon copy).

I have your changes saved locally if you need them still. Best bet to get it changed over is do a carbon copy refactor first (ie pull out classes with styles, also testing with a single video and also with a channel to test both functionality). 

Once everything looks the same you can add changes like the <code> block, if that makes sense, thanks!

**Comment by pjobson** [comment]
I don't need them, I just did up the style sheet, because I liked your reddit post.  I don't actually do anything with youtube-dl which isn't CLI based.

**Pull request merged**
