### PR TITLE
formatted with Prettier

### PR DESCRIPTION
**Pull request by whyboris**
Let's make it [_Prettier_](https://prettier.io/) 😉 🌸

### CODE REVIEW

**Comment by mayeaux** [comment]
Hey @whyboris , I am actually using some of your code today! From a Github issue that I found. 

Personally I prefer single quotes but the rest looks pretty good.

**Comment by whyboris** [comment]
Had to change the setting on the `Prettier` _VSCode_ settings to single quote 👌 

I think the PR is ready for re-review 👍

**Comment by mayeaux** [comment]
Thanks @whyboris , I like it! Reading through the PR made me realize how much stuff I had left uncommented 😅 but I promise I'll get around to that before too long. Thanks hope you are enjoying the module :)

**Comment by whyboris** [comment]
Also consider using _TypeScript_ 👍

**Pull request merged**
